#!/usr/bin/python3
# -*- coding: utf-8 -*-
import sys, os
here = os.path.dirname(os.path.abspath(__file__))
res  = os.path.join(os.path.dirname(here), "Resources")
sys.path.insert(0, res)
os.chdir(res)
if "--selfcheck" in sys.argv:
    import codex_setup_gui; sys.exit(codex_setup_gui.selfcheck())
import codex_setup_gui
codex_setup_gui.main()
